services:
  db:
    image: postgres:18-bookworm
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food-swipe
    volumes:
      - pg-data:/var/lib/postgresql
    ports:
      - "5432:5432"

  cache:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  follow:
    build:
      context: ./apps/follow
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3001"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/food-swipe?sslmode=disable

volumes:
  pg-data:
  redis-data:
