services:
  db:
    image: postgres:18-bookworm
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food-swipe
    volumes:
      - pg-data:/var/lib/postgresql
    ports:
      - "5432:5432"

  cache:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "-js -sd /data"
    volumes:
      - nats-data:/data
    networks: ["nats"]

volumes:
  pg-data:
  redis-data:
  nats-data:

networks:
  nats:
    name: nats
